import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// 전체 레이아웃을 위한 파일을 만들 수도 있고, 특정 레이아웃을 위한 파일을 만들 수도 있다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head/>
      <body>
        <nav>
          <Link href="/">
            Home
          </Link> &nbsp;&nbsp;
          <Link href="/posts">
            Post
          </Link>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
